version: "3"

services:
  flag3:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: flag3:0.0.1
    container_name: flag3
    restart: always
    ports:
      - "8080:8080"

